export const DATABASE_PROVIDER = 'DATABASE_PROVIDER';
export const AUTH_MODEL = 'AUTH_MODEL';
export const PERFORMER_MODEL = 'PERFORMER_MODEL';
export const PERFORMANCE_MODEL = 'PERFORMANCE_MODEL';
export const TRANSACTION_MODEL = 'TRANSACTION_MODEL';
