export const DATABASE_PROVIDER = 'DATABASE_PROVIDER';
export const USER_MODEL = 'USER_MODEL';
export const PERFORMER_MODEL = 'PERFORMER_MODEL';
export const PERFORMANCE_MODEL = 'PERFORMANCE_MODEL';
export const TRANSACTION_MODEL = 'TRANSACTION_MODEL';
